#!/usr/bin/env bash
# One-command Linux setup for ohmyvoice.
#
# Usage:
#   bash setup-linux.sh
#
# Idempotent — safe to run again after partial failure.
set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "$0")" && pwd)"
BACKEND_DIR="${PROJECT_DIR}/contrib/sensevoice-backend"
VENV_DIR="${BACKEND_DIR}/.venv"
BIN_DIR="${HOME}/.local/bin"
STATE_DIR="${XDG_STATE_HOME:-${HOME}/.local/state}/ohmyvoice"
HYPR_DIR="${XDG_CONFIG_HOME:-${HOME}/.config}/hypr"
HYPR_MAIN_CONFIG="${HYPR_DIR}/hyprland.conf"
HYPR_SNIPPET="${HYPR_DIR}/ohmyvoice.conf"
HYPR_AUTOCONFIG="${OHMYVOICE_HYPRLAND_AUTOCONFIG:-1}"

echo "=== ohmyvoice Linux setup ==="
echo ""

echo "[1/5] Checking dependencies..."

missing=()
for cmd in node npm ffmpeg python3 pw-record pw-play wl-copy notify-send curl tar; do
  command -v "${cmd}" >/dev/null 2>&1 || missing+=("${cmd}")
done

if [ ${#missing[@]} -gt 0 ]; then
  echo ""
  echo "Missing dependencies: ${missing[*]}"
  echo ""
  echo "Install them with your package manager, or re-run install-linux.sh."
  exit 1
fi

if [ "$(node -p "process.versions.node.split('.')[0]")" -lt 20 ]; then
  echo "Node.js 20+ is required. Current version: $(node --version)" >&2
  exit 1
fi

echo "  All dependencies found."

echo "[2/5] Building project..."
cd "${PROJECT_DIR}"
npm ci --silent
npm run build
echo "  Build complete."

echo "[3/5] Setting up Python backend..."
if [ ! -d "${VENV_DIR}" ]; then
  python3 -m venv "${VENV_DIR}"
  echo "  Created venv at ${VENV_DIR}"
fi

"${VENV_DIR}/bin/pip3" install -q -r "${BACKEND_DIR}/requirements.txt"
echo "  Python dependencies installed."

echo "[4/5] Checking SenseVoice model..."
if [ -f "${BACKEND_DIR}/model/model.int8.onnx" ]; then
  echo "  Model already downloaded."
else
  echo "  Downloading SenseVoice-Small model (~228 MB)..."
  bash "${BACKEND_DIR}/download_model.sh"
fi

echo "[5/5] Installing user wrappers..."

mkdir -p "${BIN_DIR}" "${STATE_DIR}"

cat > "${BIN_DIR}/voicectl" <<EOF
#!/usr/bin/env bash
set -euo pipefail

node_major() {
  if ! command -v node >/dev/null 2>&1; then
    echo 0
    return
  fi

  node -p "process.versions.node.split('.')[0]"
}

if [ "\$(node_major)" -lt 20 ]; then
  echo "Node.js 20+ is required. Current node on PATH: \$(command -v node 2>/dev/null || echo missing)" >&2
  exit 1
fi

exec node "${PROJECT_DIR}/dist/cli.js" "\$@"
EOF

cat > "${BIN_DIR}/voice-daemon" <<EOF
#!/usr/bin/env bash
set -euo pipefail

node_major() {
  if ! command -v node >/dev/null 2>&1; then
    echo 0
    return
  fi

  node -p "process.versions.node.split('.')[0]"
}

if [ "\$(node_major)" -lt 20 ]; then
  echo "Node.js 20+ is required. Current node on PATH: \$(command -v node 2>/dev/null || echo missing)" >&2
  exit 1
fi

export VOICE_BACKEND="\${VOICE_BACKEND:-managed}"
export VOICE_ENDPOINT="\${VOICE_ENDPOINT:-http://127.0.0.1:8000/v1/chat/completions}"
exec node "${PROJECT_DIR}/dist/daemon.js" "\$@"
EOF

cat > "${BIN_DIR}/ohmyvoice-ensure-daemon" <<EOF
#!/usr/bin/env bash
set -euo pipefail

if "${BIN_DIR}/voicectl" status >/dev/null 2>&1; then
  exit 0
fi

mkdir -p "${STATE_DIR}"
nohup "${BIN_DIR}/voice-daemon" > "${STATE_DIR}/daemon.log" 2>&1 < /dev/null &
disown || true
EOF

chmod +x "${BIN_DIR}/voicectl" "${BIN_DIR}/voice-daemon" "${BIN_DIR}/ohmyvoice-ensure-daemon"
echo "  Installed wrappers to ${BIN_DIR}"

if [ "${HYPR_AUTOCONFIG}" = "1" ] && { [ -d "${HYPR_DIR}" ] || [ -n "${HYPRLAND_INSTANCE_SIGNATURE:-}" ]; }; then
  mkdir -p "${HYPR_DIR}"
  cat > "${HYPR_SNIPPET}" <<EOF
# Generated by setup-linux.sh — safe to re-run.
# Keep this file in place while hyprland.conf sources it.
\$ohmyvoice_voicectl = ${BIN_DIR}/voicectl
\$ohmyvoice_ensure_daemon = ${BIN_DIR}/ohmyvoice-ensure-daemon

exec-once = \$ohmyvoice_ensure_daemon
bind = , code:66, exec, \$ohmyvoice_voicectl start
bindr = , code:66, exec, \$ohmyvoice_voicectl stop
EOF

  source_line="source = ${HYPR_SNIPPET}"
  if [ -f "${HYPR_MAIN_CONFIG}" ]; then
    if ! grep -qxF "${source_line}" "${HYPR_MAIN_CONFIG}" 2>/dev/null; then
      printf "\n%s\n" "${source_line}" >> "${HYPR_MAIN_CONFIG}"
    fi
  else
    printf "%s\n" "${source_line}" > "${HYPR_MAIN_CONFIG}"
  fi

  if command -v hyprctl >/dev/null 2>&1; then
    hyprctl reload >/dev/null 2>&1 || true
  fi

  echo "  Hyprland integration written to ${HYPR_SNIPPET}"
elif [ "${HYPR_AUTOCONFIG}" != "1" ]; then
  echo "  Hyprland auto-config disabled (OHMYVOICE_HYPRLAND_AUTOCONFIG=${HYPR_AUTOCONFIG})."
else
  echo "  Hyprland not detected; skipping hotkey config."
fi

echo ""
echo "========================================="
echo "  ohmyvoice setup complete!"
echo "========================================="
echo ""
echo "Usage:"
echo "  ${BIN_DIR}/ohmyvoice-ensure-daemon"
echo "  ${BIN_DIR}/voicectl start"
echo "  ${BIN_DIR}/voicectl stop"
echo ""
if [ "${HYPR_AUTOCONFIG}" = "1" ] && { [ -d "${HYPR_DIR}" ] || [ -n "${HYPRLAND_INSTANCE_SIGNATURE:-}" ]; }; then
  echo "Hold CapsLock to record, release to stop."
elif [ "${HYPR_AUTOCONFIG}" != "1" ]; then
  echo "Hyprland auto-config is disabled."
  echo "Re-run with OHMYVOICE_HYPRLAND_AUTOCONFIG=1 if you want the script to write a CapsLock binding."
else
  echo "If you use Hyprland, source ${HYPR_SNIPPET} from your config to add a CapsLock hotkey."
  echo "Set OHMYVOICE_HYPRLAND_AUTOCONFIG=1 before running setup-linux.sh to let the script write it for you."
fi
echo ""
if [[ ":${PATH}:" != *":${BIN_DIR}:"* ]]; then
  echo "Note: ${BIN_DIR} is not on PATH in this shell."
fi
