#!/usr/bin/env bash
# Install ohmyvoice Hammerspoon integration on macOS.
#
# Idempotent — safe to run multiple times.
# Does NOT overwrite existing Hammerspoon config; appends require() if needed.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(cd "${SCRIPT_DIR}/../.." && pwd)"
HS_DIR="${HOME}/.hammerspoon"
HS_INIT="${HS_DIR}/init.lua"

node_major() {
  local node_bin="${1:-}"
  if [ -z "${node_bin}" ] || [ ! -x "${node_bin}" ]; then
    echo 0
    return
  fi

  "${node_bin}" -p "process.versions.node.split('.')[0]"
}

resolve_node_bin() {
  local brew_prefix

  if [ -n "${OHMYVOICE_NODE_BIN:-}" ] && [ -x "${OHMYVOICE_NODE_BIN}" ]; then
    printf '%s\n' "${OHMYVOICE_NODE_BIN}"
    return 0
  fi

  if command -v brew >/dev/null 2>&1; then
    brew_prefix="$(brew --prefix node 2>/dev/null || true)"
    if [ -n "${brew_prefix}" ] && [ -x "${brew_prefix}/bin/node" ]; then
      printf '%s\n' "${brew_prefix}/bin/node"
      return 0
    fi
  fi

  if command -v node >/dev/null 2>&1; then
    command -v node
    return 0
  fi

  return 1
}

# --------------------------------------------------------------------------
# 1. Check prerequisites
# --------------------------------------------------------------------------

missing=()
NODE_BIN="$(resolve_node_bin || true)"

if [ -z "${NODE_BIN}" ]; then
  missing+=("node (brew install node)")
else
  export OHMYVOICE_NODE_BIN="${NODE_BIN}"
  export PATH="$(dirname "${NODE_BIN}"):${PATH}"
fi

command -v ffmpeg >/dev/null 2>&1 || missing+=("ffmpeg (brew install ffmpeg)")
command -v python3 >/dev/null 2>&1 || missing+=("python3 (brew install python3)")

if [ ${#missing[@]} -gt 0 ]; then
  echo "Missing dependencies:"
  for dep in "${missing[@]}"; do
    echo "  - $dep"
  done
  exit 1
fi

if [ "$(node_major "${NODE_BIN}")" -lt 20 ]; then
  echo "Node.js 20+ is required. Current version: $("${NODE_BIN}" --version)" >&2
  exit 1
fi

if ! [ -d "/Applications/Hammerspoon.app" ] && ! [ -d "${HOME}/Applications/Hammerspoon.app" ]; then
  echo "Hammerspoon not found. Install it:"
  echo "  brew install --cask hammerspoon"
  exit 1
fi

# --------------------------------------------------------------------------
# 3. Generate ohmyvoice.lua with correct paths
# --------------------------------------------------------------------------

mkdir -p "${HS_DIR}"

cat > "${HS_DIR}/ohmyvoice.lua" << LUAEOF
-- ohmyvoice: push-to-talk voice input for macOS
-- Generated by contrib/macos/install.sh — safe to re-run.

local nodeBin      = "${NODE_BIN}"
local projectDir   = "${PROJECT_DIR}"
local daemonScript = projectDir .. "/dist/daemon.js"
local cliScript    = projectDir .. "/dist/cli.js"

----------------------------------------------------------------
-- Daemon process (managed by Hammerspoon)
----------------------------------------------------------------

local socketPath     = "/tmp/ohmyvoice.sock"
local backendPidFile = "/tmp/ohmyvoice-backend.pid"
local backendScript  = projectDir .. "/contrib/sensevoice-backend/server.py"

-- Kill stale backend by PID file, but only after verifying the PID still
-- belongs to our server.py (guards against PID reuse after a crash).
local function killByPidFile(pidFile, scriptPath)
  local f = io.open(pidFile, "r")
  if not f then return end
  local pid = f:read("*a"):match("^%s*(%d+)%s*\$")
  f:close()
  if not pid then
    os.remove(pidFile)
    return
  end
  local cmd = hs.execute("ps -p " .. pid .. " -o command= 2>/dev/null")
  if not cmd or not cmd:find(scriptPath, 1, true) then
    hs.printf("ohmyvoice: stale pid %s is not our backend, skipping kill", pid)
    os.remove(pidFile)
    return
  end
  hs.execute("kill -TERM -" .. pid .. " 2>/dev/null; kill -TERM " .. pid .. " 2>/dev/null")
  os.remove(pidFile)
end

killByPidFile(backendPidFile, backendScript)
hs.execute("pkill -f 'node.*ohmyvoice/dist/daemon.js' 2>/dev/null; rm -f " .. socketPath)
hs.timer.usleep(300000)

local daemonEnv = {
  PATH           = "${NODE_BIN%/*}:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin",
  LANG           = "en_US.UTF-8",
  HOME           = os.getenv("HOME"),
  VOICE_ENDPOINT = "http://127.0.0.1:8000/v1/chat/completions",
}

local function startDaemon()
  local task = hs.task.new(nodeBin, function(code, _, stderr)
    hs.printf("ohmyvoice daemon exited: code=%d stderr=%s", code, stderr)
    hs.timer.doAfter(2, startDaemon)
  end, {daemonScript})
  task:setEnvironment(daemonEnv)
  task:start()
  hs.printf("ohmyvoice daemon started, pid=%s", tostring(task:pid()))
end

startDaemon()

----------------------------------------------------------------
-- Hotkey: hold Right Command -> record, release -> stop
----------------------------------------------------------------
local rightCmdDown = false

voiceTap = hs.eventtap.new(
  {hs.eventtap.event.types.flagsChanged},
  function(event)
    if event:getKeyCode() ~= 54 then return false end
    local flags = event:getFlags()

    if flags.cmd and not rightCmdDown then
      rightCmdDown = true
      hs.task.new(nodeBin, nil, {cliScript, "start"}):start()
      return true
    elseif not flags.cmd and rightCmdDown then
      rightCmdDown = false
      hs.task.new(nodeBin, nil, {cliScript, "stop"}):start()
      return true
    end
    return false
  end
)
voiceTap:start()

hs.timer.doEvery(5, function()
  if not voiceTap:isEnabled() then
    hs.printf("ohmyvoice: event tap was disabled, re-enabling")
    voiceTap:stop()
    voiceTap:start()
  end
end)
LUAEOF

echo "Generated ${HS_DIR}/ohmyvoice.lua"

# --------------------------------------------------------------------------
# 4. Wire into init.lua (idempotent)
# --------------------------------------------------------------------------

if [ -f "${HS_INIT}" ]; then
  if grep -qF 'require("ohmyvoice")' "${HS_INIT}" 2>/dev/null; then
    echo "init.lua already requires ohmyvoice — skipping."
  elif grep -qE 'ohmyvoice|voiceTap' "${HS_INIT}" 2>/dev/null; then
    echo ""
    echo "WARNING: ${HS_INIT} contains existing ohmyvoice code (inline, not via require)."
    echo "Adding require(\"ohmyvoice\") would conflict with it (double daemon, double hotkey)."
    echo ""
    echo "To fix, replace the inline ohmyvoice code in init.lua with:"
    echo "  require(\"ohmyvoice\")"
    echo ""
    echo "Skipping init.lua modification. Generated ohmyvoice.lua is ready to use."
  else
    echo '' >> "${HS_INIT}"
    echo 'require("ohmyvoice")' >> "${HS_INIT}"
    echo "Appended require(\"ohmyvoice\") to ${HS_INIT}"
  fi
else
  echo 'require("ohmyvoice")' > "${HS_INIT}"
  echo "Created ${HS_INIT}"
fi

# --------------------------------------------------------------------------
# 5. Reload Hammerspoon (best-effort)
# --------------------------------------------------------------------------

if pgrep -x Hammerspoon >/dev/null 2>&1; then
  hs -c 'hs.reload()' 2>/dev/null && echo "Hammerspoon reloaded." || echo "Could not reload Hammerspoon automatically. Please reload manually via the menubar icon."
else
  echo "Hammerspoon is not running. Start it and it will load ohmyvoice automatically."
fi

echo ""
echo "Done. Next steps:"
echo "  1. Grant Accessibility to Hammerspoon: System Settings > Privacy & Security > Accessibility"
echo "  2. Grant Microphone access when prompted on first recording"
echo "  3. Hold Right Command to record, release to stop"
